alias: get-ml-model-whisper
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML models
env:
  MLC_ML_MODEL_WEIGHT_TRANSFORMATIONS: 'no'
  MLC_ML_MODEL_DATASET: whisper
input_mapping:
  checkpoint: WHISPER_CHECKPOINT_PATH
new_env_keys:
- MLC_ML_MODEL_*
- WHISPER_CHECKPOINT_PATH
- MLC_WHISPER_FINAL_SAFE_TENSORS_PATH
print_env_at_the_end:
  WHISPER_CHECKPOINT_PATH: Whisper checkpoint path
tags:
- get-ml-model-whisper
- get
- ml-model
- whisper
- speech-recognition
tests:
  run_inputs:
  - variations_list:
    - huggingface,dry-run

uid: 3bea2356e97f47b1

prehook_deps:
- enable_if_env:
    MLC_TMP_REQUIRE_DOWNLOAD:
    - 'yes'
    MLC_DOWNLOAD_SRC:
    - 'huggingface'
  env: {}
  extra_cache_tags: whisper
  force_env_keys:
  - MLC_GIT_CHECKOUT_FOLDER
  names:
  - hf-zoo
  tags: get,ml-model,huggingface,zoo,_clone-repo
  force_env_keys:
    - MLC_OUTDIRNAME

variations:
  fp32:
    default: true
    env:
      MLC_ML_MODEL_INPUT_DATA_TYPES: fp32
      MLC_ML_MODEL_PRECISION: fp32
      MLC_ML_MODEL_WEIGHT_DATA_TYPES: fp32
    group: precision

  huggingface:
    group: download-source
    env:
      MLC_DOWNLOAD_SRC: huggingface

  large-v3:
    env:
      MLC_GIT_CHECKOUT_FOLDER: whisper-large-v3
    group: model-size
    default: true
    default_variations:
      huggingface-stub: openai/whisper-large-v3

  openai/whisper-large-v3:
    base:
      - large-v3
    adr:
      hf-zoo:
        tags: _model-stub.openai/whisper-large-v3
    env:
      MLC_MODEL_ZOO_ENV_KEY: WHISPER
    group: huggingface-stub

  dry-run:
    env:
      MLC_DOWNLOAD_MODE: dry
    group: run-mode
  dry-run,rclone:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: --dry-run
  dry-run,r2-downloader:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: -x