alias: get-ml-model-rgat
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML models
docker:
  fake_run_deps: True
env:
  MLC_ML_MODEL: RGAT
input_mapping:
  checkpoint: RGAT_CHECKPOINT_PATH
new_env_keys:
- MLC_ML_MODEL_*
- MLC_ML_MODEL_RGAT_CHECKPOINT_PATH
- RGAT_CHECKPOINT_PATH
prehook_deps:
- enable_if_env:
    MLC_TMP_REQUIRE_DOWNLOAD:
    - 'yes'
  env:
    MLC_DOWNLOAD_FINAL_ENV_NAME: RGAT_DIR_PATH
  extra_cache_tags: rgat,gnn,model,ml-model
  force_cache: true
  names:
  - download-rgat-model-file
  tags: download,file
  force_env_keys:
    - MLC_OUTDIRNAME
  update_tags_from_env_with_prefix:
    _url.:
    - MLC_DOWNLOAD_URL
print_env_at_the_end:
  RGAT_CHECKPOINT_PATH: R-GAT checkpoint path
tags:
- get
- raw
- ml-model
- rgat
uid: b409fd66c5ad4ed5
variations:
  pytorch:
    default: true
  fp32:
    default: true
    env:
      MLC_ML_MODEL_INPUT_DATA_TYPES: fp32
      MLC_ML_MODEL_PRECISION: fp32
      MLC_ML_MODEL_WEIGHT_DATA_TYPES: fp32
    group: precision
  mlcommons:
    default: true
    default_variations:
      download-tool: r2-downloader
    group: download-source
  rclone:
    adr:
      download-rgat-model-file:
        tags: _rclone
    env:
      MLC_DOWNLOAD_TOOL: rclone
      MLC_RCLONE_CONFIG_NAME: mlc-inference
    group: download-tool
  r2-downloader:
    adr:
      download-rgat-model-file:
        tags: _r2-downloader
    env:
      MLC_DOWNLOAD_TOOL: r2-downloader
    group: download-tool
  rclone,mlcommons,fp32:
    env:
      MLC_ML_MODEL_STARTING_WEIGHTS_FILENAME: https://github.com/mlcommons/inference/tree/master/graph/R-GAT#download-model-using-rclone
      MLC_DOWNLOAD_URL: mlc-inference:mlcommons-inference-wg-public/R-GAT/RGAT.pt
      MLC_DOWNLOAD_FILENAME: RGAT
  r2-downloader,mlcommons,fp32:
    env:
      MLC_ML_MODEL_STARTING_WEIGHTS_FILENAME: https://github.com/mlcommons/inference/tree/master/graph/R-GAT#download-model-using-mlc-r2-downloader
      MLC_DOWNLOAD_URL: https://inference.mlcommons-storage.org/metadata/rgat-model.uri
      MLC_DOWNLOAD_FILENAME: RGAT
