alias: get-ml-model-mixtral
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML models
env:
  MLC_ML_MODEL_DATASET: ''
  MLC_ML_MODEL_WEIGHT_TRANSFORMATIONS: 'no'
docker:
  real_run: False
input_mapping:
  checkpoint: MIXTRAL_CHECKPOINT_PATH
new_env_keys:
- MLC_ML_MODEL_*
- MIXTRAL_CHECKPOINT_PATH
prehook_deps:
- enable_if_env:
    MLC_TMP_REQUIRE_DOWNLOAD:
    - 'yes'
  skip_if_env:
    MLC_DOWNLOAD_TOOL: 
    - r2-downloader
  env: {}
  extra_cache_tags: mixtral
  force_env_keys:
  - MLC_GIT_CHECKOUT_FOLDER
  names:
  - hf-zoo
  tags: get,ml-model,huggingface,zoo,_clone-repo
  force_env_keys:
    - MLC_OUTDIRNAME  
print_env_at_the_end:
  MIXTRAL_CHECKPOINT_PATH: MIXTRAL checkpoint path
tags:
- get
- raw
- ml-model
- language-processing
- mixtral
- mixtral-8x7b
uid: 0c14127677f34ea2
variations:
  batch_size.#:
    env:
      MLC_ML_MODEL_BATCH_SIZE: '#'
  fp32:
    default: true
    env:
      MLC_ML_MODEL_INPUT_DATA_TYPES: fp32
      MLC_ML_MODEL_PRECISION: fp32
      MLC_ML_MODEL_WEIGHT_DATA_TYPES: fp32
    group: precision
  mistralai/Mixtral-8x7B-Instruct-v0.1:
    adr:
      hf-zoo:
        tags: _model-stub.mistralai/Mixtral-8x7B-Instruct-v0.1
    default: true
    env:
      MLC_GIT_CHECKOUT_FOLDER: Mixtral-8x7B-Instruct-v0.1
      MLC_ML_MODEL_STARTING_WEIGHTS_FILENAME: https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1
      MLC_MODEL_ZOO_ENV_KEY: MIXTRAL
    group: huggingface-stub
  mlc:
    prehook_deps:
      - env:
          MLC_DOWNLOAD_FINAL_ENV_NAME: MIXTRAL_CHECKPOINT_PATH
          MLC_EXTRACT_FINAL_ENV_NAME: MIXTRAL_CHECKPOINT_PATH
        extra_cache_tags: ml-model,mixtral,raw,ml-model-mixtral
        force_cache: true
        names:
        - dae-mixtral-model
        enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
            - 'yes'
        tags: download-and-extract
        force_env_keys:
          - MLC_OUTDIRNAME  
        update_tags_from_env_with_prefix:
          _url.:
          - MLC_PACKAGE_URL
  mlc,r2-downloader:
    env:
      MLC_DOWNLOAD_URL: https://inference.mlcommons-storage.org/metadata/mixtral-8x7b-model-checkpoint.uri
      MLC_ML_MODEL_STARTING_WEIGHTS_FILENAME: ""
  r2-downloader:
    adr:
      dae-mixtral-model:
        tags: _r2-downloader
    env:
      MLC_DOWNLOAD_TOOL: r2-downloader
    group: download-tool
  dry-run:
    group: run-mode
    env:
      MLC_DOWNLOAD_MODE: dry
  dry-run,r2-downloader:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: -x
  pytorch:
    default: true
    env:
      MLC_ML_MODEL_FRAMEWORK: pytorch
    group: framework
  stub.#:
    adr:
      hf-zoo:
        tags: _model-stub.#
    env:
      MLC_MODEL_ZOO_ENV_KEY: MIXTRAL
    group: huggingface-stub
tests:
  run_inputs:
  - variations_list:
    - r2-downloader,mlc,dry-run
