alias: get-ml-model-stable-diffusion
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML models
env:
  MLC_ML_MODEL: SDXL
  MLC_ML_MODEL_DATASET: openorca
  MLC_ML_MODEL_WEIGHT_TRANSFORMATIONS: 'no'
input_mapping:
  checkpoint: SDXL_CHECKPOINT_PATH
  download_path: MLC_DOWNLOAD_PATH
  to: MLC_DOWNLOAD_PATH
new_env_keys:
- MLC_ML_MODEL_*
- SDXL_CHECKPOINT_PATH
prehook_deps:
- enable_if_env:
    MLC_DOWNLOAD_TOOL:
    - git
    MLC_TMP_REQUIRE_DOWNLOAD:
    - 'yes'
  env:
    MLC_GIT_CHECKOUT_FOLDER: stable-diffusion-xl-base-1.0
    MLC_MODEL_ZOO_ENV_KEY: SDXL
  force_env_keys:
  - MLC_GIT_CHECKOUT_FOLDER
  names:
  - hf-zoo
  tags: get,ml-model,huggingface,zoo,_clone-repo,_model-stub.stabilityai/stable-diffusion-xl-base-1.0
  force_env_keys:
    - MLC_OUTDIRNAME  
- enable_if_env:
    MLC_DOWNLOAD_SOURCE:
    - mlcommons
    MLC_TMP_REQUIRE_DOWNLOAD:
    - 'yes'
  env:
    MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_ML_MODEL_PATH
  extra_cache_tags: stable-diffusion,sdxl,model
  force_cache: true
  names:
  - dae-sdxl-model
  tags: download-and-extract
  update_tags_from_env_with_prefix:
    _url.:
    - MLC_DOWNLOAD_URL
print_env_at_the_end:
  SDXL_CHECKPOINT_PATH: Stable diffusion checkpoint path
tags:
- get
- raw
- ml-model
- stable-diffusion
- sdxl
- text-to-image
uid: 22c6516b2d4d4c23
variations:
  batch_size.#:
    env:
      MLC_ML_MODEL_BATCH_SIZE: '#'
  fp16:
    env:
      MLC_ML_MODEL_INPUT_DATA_TYPES: fp16
      MLC_ML_MODEL_PRECISION: fp16
      MLC_ML_MODEL_WEIGHT_DATA_TYPES: fp16
    group: precision
  fp32:
    default: true
    env:
      MLC_ML_MODEL_INPUT_DATA_TYPES: fp32
      MLC_ML_MODEL_PRECISION: fp32
      MLC_ML_MODEL_WEIGHT_DATA_TYPES: fp32
    group: precision
  git:
    env:
      MLC_DOWNLOAD_TOOL: git
    group: download-tool
  huggingface:
    default_variations:
      download-tool: git
    group: download-source
  int8:
    env:
      MLC_ML_MODEL_INPUT_DATA_TYPES: int8
      MLC_ML_MODEL_PRECISION: int8
      MLC_ML_MODEL_WEIGHT_DATA_TYPES: int8
    group: precision
  mlcommons:
    default: true
    default_variations:
      download-tool: r2-downloader
    env:
      MLC_DOWNLOAD_SOURCE: mlcommons
    group: download-source
  pytorch:
    default: true
    env:
      MLC_ML_MODEL_FRAMEWORK: pytorch
      MLC_ML_MODEL_STARTING_WEIGHTS_FILENAME: https://github.com/mlcommons/inference/tree/master/text_to_image#download-model
    group: framework
  pytorch,fp16:
    required_disk_space: 6500
  pytorch,fp32:
    env: {}
    required_disk_space: 13000
  rclone:
    adr:
      dae-sdxl-model:
        tags: _rclone
    env:
      MLC_DOWNLOAD_TOOL: rclone
      MLC_RCLONE_CONFIG_NAME: mlc-inference
    group: download-tool
  r2-downloader:
    adr:
      dae-sdxl-model:
        tags: _r2-downloader
    env:
      MLC_DOWNLOAD_TOOL: r2-downloader
    group: download-tool
  rclone,fp16:
    env:
      MLC_DOWNLOAD_URL: mlc-inference:mlcommons-inference-wg-public/stable_diffusion_fp16
  rclone,fp32:
    env:
      MLC_DOWNLOAD_URL: mlc-inference:mlcommons-inference-wg-public/stable_diffusion_fp32
  r2-downloader,fp16:
    env:
      MLC_DOWNLOAD_URL: https://inference.mlcommons-storage.org/metadata/stable-diffusion-xl-1-0-fp16-checkpoint.uri
      MLC_DOWNLOAD_FILENAME: fp16-checkpoint
  r2-downloader,fp32:
    env:
      MLC_DOWNLOAD_URL: https://inference.mlcommons-storage.org/metadata/stable-diffusion-xl-1-0-fp32-checkpoint.uri
      MLC_DOWNLOAD_FILENAME: fp32-checkpoint
  uint8:
    env:
      MLC_ML_MODEL_INPUT_DATA_TYPES: uint8
      MLC_ML_MODEL_PRECISION: uint8
      MLC_ML_MODEL_WEIGHT_DATA_TYPES: uint8
    group: precision
  wget:
    adr:
      dae-sdxl-model:
        tags: _wget
    env:
      MLC_DOWNLOAD_TOOL: wget
    group: download-tool
  dry-run:
    group: run-mode
    env:
      MLC_DOWNLOAD_MODE: dry
  dry-run,rclone:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: --dry-run
  dry-run,r2-downloader:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: -x
test:
  run_inputs:
    - variations_list:
      - fp32,r2-downloader,dry-run
      - fp16,r2-downloader,dry-run
