alias: get-preprocessed-dataset-openorca
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML datasets
category_sort: 8500
default_env:
  MLC_DATASET_CALIBRATION: 'no'
deps:
- tags: get,sys-utils-mlc
  skip_if_env:
    MLC_DATASET_PREPROCESSED_BY_MLC:
    - 'on'
    - 'yes'
- names:
  - python
  - python3
  tags: get,python3
- names:
  - openorca-original
  - dataset-original
  skip_if_env:
    MLC_DATASET_PREPROCESSED_BY_MLC:
    - 'on'
    - 'yes'
  tags: get,dataset,original,openorca
- force_env_keys:
  - MLC_GIT_*
  names:
  - inference-src
  skip_if_env:
    MLC_DATASET_PREPROCESSED_BY_MLC:
    - 'on'
    - 'yes'
  tags: mlperf,inference,source
- names:
  - pyarrow
  tags: get,generic-python-lib,_package.pyarrow
- names:
  - fastparquet
  tags: get,generic-python-lib,_package.fastparquet
- names:
  - transformers
  tags: get,generic-python-lib,_package.transformers
- names:
  - datasets
  tags: get,generic-python-lib,_package.datasets
  version_max: 2.19.2
  enable_if_env:
    MLC_DATASET_PREPROCESSED_BY_MLC:
    - 'on'
    - 'yes'
- names:
  - numpy
  tags: get,generic-python-lib,_package.numpy
  version_max: 1.26.4
  enable_if_env:
    MLC_DATASET_PREPROCESSED_BY_MLC:
    - 'on'
    - 'yes'
- names:
  - pandas
  tags: get,generic-python-lib,_package.pandas
  version_max: 2.2.2
  enable_if_env:
    MLC_DATASET_PREPROCESSED_BY_MLC:
    - 'on'
    - 'yes'
- skip_if_env:
    MLC_DATASET_PREPROCESSED_BY_MLC:
    - 'on'
    - 'yes'
  tags: get,ml-model,llama2
docker:
  real_run: false
env:
  MLC_DATASET: OPENORCA
tags:
- get
- dataset
- openorca
- language-processing
- preprocessed
uid: 5614c39cb1564d72
variations:
  '60':
    ad:
      dataset-original:
        tags: _60
    group: size
  calibration:
    base:
    - mlcommons
    env:
      MLC_DATASET_CALIBRATION: 'yes'
    group: dataset-type
    new_env_keys:
    - MLC_DATASET_CALIBRATION_PATH
    - MLC_DATASET_OPENORCA_CALIBRATION_PATH
  full:
    ad:
      dataset-original:
        tags: _full
    default: true
    group: size
  mlc:
    alias: mlcommons
  r2-downloader:
    add_deps_recursive:
      dae-openorca:
        tags: _r2-downloader
    group: download-tool
    default: true
  dry-run:
    group: run-mode
    env:
      MLC_DOWNLOAD_MODE: dry
  rclone:
    add_deps_recursive:
      dae-openorca:
        tags: _rclone
    group: download-tool
  dry-run,r2-downloader:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: -x
  dry-run,rclone:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: --dry-run
  mlcommons:
    default: true
    deps:
    - env:
        MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_OPENORCA_PREPROCESSED_ROOT
        MLC_EXTRACT_FINAL_ENV_NAME: MLC_OPENORCA_PREPROCESSED_ROOT
        MLC_EXTRACT_TO_FOLDER: openorca-preprocessed
      extra_cache_tags: openorca,preprocessed,dataset
      force_cache: true
      names:
      - dae-openorca
      tags: download-and-extract
      force_env_keys:
        - MLC_OUTDIRNAME  
      update_tags_from_env_with_prefix:
        _url.:
        - MLC_DOWNLOAD_URL
    env:
      MLC_DATASET_PREPROCESSED_BY_MLC: 'yes'
      MLC_RCLONE_URL: mlc-inference:mlcommons-inference-wg-public/open_orca
  r2-downloader,mlcommons:
    env:
      MLC_DOWNLOAD_URL: https://inference.mlcommons-storage.org/metadata/llama-2-70b-open-orca-dataset.uri
  rclone,mlcommons:
    env:
      MLC_DOWNLOAD_URL: mlc-inference:mlcommons-inference-wg-public/open_orca
      MLC_RCLONE_CONFIG_NAME: mlc-inference
  size.#:
    ad:
      dataset-original:
        tags: _size.#
    group: size
  validation:
    default: true
    env:
      MLC_DATASET_CALIBRATION: 'no'
    group: dataset-type
    new_env_keys:
    - MLC_DATASET_PREPROCESSED_PATH
    - MLC_DATASET_OPENORCA_PREPROCESSED_PATH
    - PREPROCESSED_DATA_DIR
  nvidia:
    group: preprocess-step-provider
    env:
      MLC_TMP_DATASET_PREPROCESS_STEP_PROVIDER: nvidia
  nvidia,calibration:
    new_env_keys:
    - MLC_NVIDIA_PREPROCESSED_CALIBRATION_DATASET_PATH
  nvidia,validation:
    new_env_keys:
    - MLC_DATASET_OPENORCA_NVIDIA_PREPROCESSED_PATH
tests:
  run_inputs:
  - variations_list:
    - r2-downloader,mlc,dry-run
    - rclone,mlc,dry-run
