alias: get-aocc
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
clean_files: []
deps:
- tags: detect,os
- tags: download,file,_mlcutil
  extra_cache_tags: aocc,download
  update_tags_from_env_with_prefix:
    _url.:
      - MLC_AOCC_URL
  force_cache: true
  env:
    MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_AOCC_TAR_FILE_PATH
  enable_if_env:
    MLC_AOCC_URL:
      - on
    MLC_AOCC_ACCEPT_EULA:
      - on
- tags: extract,file
  update_tags_from_env_with_prefix:
    _path.:
      - MLC_AOCC_TAR_FILE_PATH
  extra_cache_tags: aocc,extract
  force_cache: true
  env:
    MLC_EXTRACT_FINAL_ENV_NAME: MLC_AOCC_DIR_PATH
    MLC_EXTRACT_TO_FOLDER: aocc_install
  enable_if_env:
    MLC_AOCC_NEEDS_TAR:
      - yes

input_mapping:
  tar_file_path: MLC_AOCC_TAR_FILE_PATH
  aocc_dir: MLC_AOCC_DIR_PATH
  accept_eula: MLC_AOCC_ACCEPT_EULA

name: Detect or install AOCC compiler
new_env_keys:
- MLC_AOCC_*
- MLC_C_COMPILER_*
- MLC_CXX_COMPILER_*
- MLC_COMPILER_*
- MLC_LINKER_*
- + CFLAGS
- + CXXFLAGS
- + FFLAGS
- + LDFLAGS
- +MLC_HOST_OS_DEFAULT_INCLUDE_PATH
- +PATH
post_deps_off:
- tags: get,compiler-flags
sort: 500
tags:
- compiler
- get
- aocc
uid: 1ceb0656e99a44ec
versions:
  5.0.0:
    env:
      MLC_AOCC_URL: https://download.amd.com/developer/eula/aocc/aocc-5-0/aocc-compiler-5.0.0.tar
      MLC_DOWNLOAD_CHECKSUM: 966fac2d2c759e9de6e969c10ada7a7b306c113f7f1e07ea376829ec86380daa
      MLC_AOCC_NEEDS_TAR: yes
      MLC_VERSION: '5.0.0-Build#1377' 
variations:
  path.#:
    env:
      MLC_AOCC_DIR_PATH: '#'
