alias: detect-os
automation_alias: script
automation_uid: 5b4e0237da074764
category: Platform information
cache: true
cache_expiration: 1h
clean_files:
- tmp-run.out
new_env_keys:
- MLC_HOST_OS_*
- +MLC_HOST_OS_*
- MLC_HOST_PLATFORM_*
- MLC_HOST_PYTHON_*
- MLC_HOST_SYSTEM_NAME
- MLC_RUN_STATE_DOCKER
- +PATH
new_state_keys:
- os_uname_*
post_deps:
- enable_if_env:
    MLC_HOST_OS_TYPE:
    - windows
  skip_if_env:
    MLC_WINDOWS_SYS_UTILS_MIN_INSTALL:
    - 'yes'
  tags: get,sys-utils-min
tags:
- detect-os
- detect
- os
- info
uid: 863735b7db8c44fc
