alias: get-lib-armpl
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Detection or installation of tools and artifacts
deps:
- tags: detect,os
new_env_keys:
- MLC_ARMPL_SRC_PATH
- MLC_ARMPL_INSTALL_PATH
- MLC_ARMPL_INCLUDE_PATH
- MLC_ARMPL_LIB_PATH
- MLC_ARMPL_VERSION
- +C_INCLUDE_PATH
- +CPLUS_INCLUDE_PATH
- +DYLD_FALLBACK_LIBRARY_PATH
- +LD_LIBRARY_PATH
prehook_deps:
  - force_cache: true
    extra_cache_tags: armpl,armpl-src
    env:
      MLC_DAE_FINAL_ENV_NAME: MLC_ARMPL_SRC_PATH
    names:
      - dae
      - dae-armpl 
    tags: download-and-extract,_extract
    force_env_keys:
      - MLC_OUTDIRNAME
    update_tags_from_env_with_prefix:
      _url.:
        - MLC_DOWNLOAD_URL
  
  - tags: extract,file
    env:
      MLC_EXTRACT_TO_FOLDER1: armpl-install
      MLC_EXTRACT_FINAL_ENV_NAME: MLC_ARMPL_INSTALL_PATH
      MLC_EXTRACT_FILE_PATH: <<<MLC_ARMPL_SRC_PATH>>>/<<<MLC_ARMPL_TAR_FILENAME>>>
    names:
      - extract  
      - extract-armpl 
    extra_cache_tags: armpl,armpl-lib
    force_cache: true
    force_env_keys:
      - MLC_OUTDIRNAME
    update_tags_from_env_with_prefix:
      _path.:
        - MLC_EXTRACT_FILE_PATH

tags:
- armpl
- lib
- get
- arm
tests:
  run_inputs:
    - {}
uid: 01ebcd701d8f480f
variations:
  version.25.07:
    default: true
    group: version
    env:
      MLC_ARMPL_VERSION: '25.07.0'
      MLC_ARMPL_TAR_FILENAME: armpl-25.07.0.tgz
      MLC_DOWNLOAD_URL: https://developer.arm.com/-/cdn-downloads/permalink/Arm-Performance-Libraries/Version_25.07/arm-performance-libraries_25.07_acfl2410.tar
